import { Platform, StyleSheet } from 'react-native'
import { responsiveFontSize, responsiveHeight, responsiveWidth } from 'react-native-responsive-dimensions'

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffff',
        borderRadius: responsiveWidth(5),
        padding: responsiveWidth(3),
        paddingTop: responsiveWidth(1),
        // paddingBottom: responsiveHeight(6),
    },
    title: {
        fontSize: Platform.OS === 'android' ? responsiveFontSize(2.8) : responsiveFontSize(3),
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: responsiveHeight(0.125),
        marginTop: 0,
        color: '#388e3c',
    },
    underline: {
        height: responsiveHeight(0.125),
        backgroundColor: '#ccc',
        width: '150%',
        alignSelf: 'center',
        marginBottom: responsiveHeight(1),
        opacity: 0.5,
    },
    userName: {
        fontSize: Platform.OS === 'android' ? responsiveFontSize(2.1) : responsiveFontSize(2.25),
        fontWeight: 'bold',
        color: '#000',
        marginBottom: responsiveHeight(1),
        textAlign: 'left',
    },
    sectionLabel: {
        fontSize: Platform.OS === 'android' ? responsiveFontSize(1.9) : responsiveFontSize(2),
        color: '#000',
        fontWeight: 'bold',
        marginBottom: responsiveHeight(1),
        textAlign: 'left',
        alignSelf: 'flex-start',
    },
    contributionBoard: {
        backgroundColor: '#fff',
        borderRadius: responsiveWidth(4),
        paddingVertical: responsiveHeight(1.25),
        paddingHorizontal: responsiveWidth(4),
        marginBottom: responsiveHeight(2),
        alignSelf: 'flex-start',
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: responsiveHeight(0.75) },
                shadowOpacity: 0.18,
                shadowRadius: responsiveWidth(3),
            },
            android: {
                elevation: 6,
            },
        }),
    },
    contributionRow: {
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    contributionBox: {
        width: responsiveWidth(9),
        height: responsiveWidth(9),
        borderRadius: responsiveWidth(2),
        marginLeft: responsiveWidth(1),
        marginRight: responsiveWidth(1),
        alignItems: 'center',
        justifyContent: 'center',
    },
    Spacer: {
        height: responsiveHeight(1.5),
    },
    petParamRow: {
        flexDirection: 'row',
        alignItems: 'stretch',
        marginBottom: responsiveHeight(3),
        width: '100%',
    },
    petParamImageWrapper: {
        justifyContent: 'center',
        alignItems: 'center',
        height: responsiveHeight(10),
        marginRight: responsiveWidth(4),
    },
    petParamImage: {
        width: responsiveWidth(25),
        height: responsiveWidth(25),
    },
    petParamInfo: {
        flex: 1,
        justifyContent: Platform.OS === 'android' ? 'flex-start' : 'center',
        height: responsiveHeight(10),
        ...Platform.select({
            android: {
                paddingVertical: 0,
                marginVertical: 0,
                marginTop: -responsiveHeight(0.5),
            },
        }),
    },
    petParamName: {
        fontSize: Platform.OS === 'android' ? responsiveFontSize(2.1) : responsiveFontSize(2.25),
        fontWeight: 'bold',
        color: '#388e3c',
        marginBottom: responsiveHeight(1.5),
        textAlign: 'left',
        ...Platform.select({
            android: {
                lineHeight: responsiveFontSize(2.1) * 1.0,
                paddingVertical: 0,
                marginTop: 0,
            },
            ios: {
                lineHeight: responsiveFontSize(2.25) * 1.1,
            },
        }),
    },
    indicatorColumn: {
        flexDirection: 'column',
        alignItems: 'flex-start',
        ...Platform.select({
            android: {
                justifyContent: 'flex-start',
                paddingVertical: 0,
                marginVertical: 0,
            },
            ios: {
                justifyContent: 'flex-start',
            },
        }),
    },
    indicatorRow: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        ...Platform.select({
            android: {
                height: responsiveHeight(2.5),
                marginBottom: responsiveHeight(0.3),
                margin: 0,
                padding: 0,
            },
            ios: {
                marginBottom: responsiveHeight(0.5),
            },
        }),
    },
    indicatorLabel: {
        fontSize: Platform.OS === 'android' ? responsiveFontSize(1.7) : responsiveFontSize(1.75),
        color: '#333',
        marginRight: responsiveWidth(2.5),
        minWidth: responsiveWidth(15),
        textAlign: 'right',
    },
    indicator: {
        height: responsiveHeight(1.25),
        borderRadius: responsiveWidth(1.25),
        flex: 1,
        minWidth: 0,
        backgroundColor: '#fff',
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: responsiveHeight(0.25) },
                shadowOpacity: 0.18,
                shadowRadius: responsiveWidth(1),
            },
            android: {
                elevation: 2,
            },
        }),
        overflow: 'visible',
        position: 'relative',
    },
    toggleContainer: {
        alignItems: 'center',
        marginBottom: responsiveHeight(2),
        width: '100%',
    },
    toggleBackground: {
        width: '100%',
        maxWidth: responsiveWidth(100),
        height: responsiveHeight(5.5),
        backgroundColor: '#fff',
        borderRadius: responsiveHeight(2.75),
        flexDirection: 'row',
        alignItems: 'center',
        position: 'relative',
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: responsiveHeight(0.25) },
                shadowOpacity: 0.12,
                shadowRadius: responsiveWidth(1.5),
            },
            android: {
                elevation: 3,
            },
        }),
    },
    toggleSlider: {
        position: 'absolute',
        top: responsiveHeight(0.5),
        height: responsiveHeight(4.5),
        backgroundColor: '#136229',
        borderRadius: responsiveHeight(2.25),
        zIndex: 1,
    },
    toggleTouchable: {
        flex: 1,
        height: responsiveHeight(5.5),
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2,
    },
    toggleText: {
        color: '#136229',
        fontWeight: 'bold',
        fontSize: responsiveFontSize(2),
    },
    activeToggleText: {
        color: '#fff',
    },
    totalRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: responsiveHeight(1),
        gap: responsiveWidth(2),
    },
    totalLabel: {
        fontSize: responsiveFontSize(1.5),
        color: '#666',
        marginBottom: responsiveHeight(0.25),
    },
    totalValue: {
        fontWeight: 'bold',
        color: '#000',
        fontSize: responsiveFontSize(2.5),
    },
    totalNumber: {
        fontSize: responsiveFontSize(4),
        fontWeight: 'bold',
        color: '#000',
    },
    totalUnit: {
        fontSize: responsiveFontSize(2),
        fontWeight: 'bold',
        color: '#000',
    },
    graphPlaceholder: {
        height: responsiveHeight(22.5),
        width: '100%',
        backgroundColor: '#f4f4f4',
        borderRadius: responsiveWidth(3),
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: responsiveHeight(3),
    },
    loadingContainer: {
        height: responsiveHeight(20),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f9f9f9',
        borderRadius: responsiveWidth(3),
        marginBottom: responsiveHeight(3),
    },
    loadingText: {
        fontSize: responsiveFontSize(1.8),
        color: '#666',
        fontWeight: '500',
    },
    chartContainer: {
        width: '100%',
        marginBottom: responsiveHeight(3),
    },
    chartArea: {
        height: responsiveHeight(20),
        backgroundColor: '#FAFAFA',
        borderRadius: responsiveWidth(2),
        padding: responsiveWidth(3),
        position: 'relative',
        flexDirection: 'row',
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: responsiveHeight(0.5) },
                shadowOpacity: 0.15,
                shadowRadius: responsiveWidth(2),
            },
            android: {
                elevation: 4,
            },
        }),
    },
    yAxisLabels: {
        width: responsiveWidth(12),
        height: responsiveHeight(15),
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        paddingRight: responsiveWidth(2),
        marginTop: responsiveHeight(1),
    },
    yAxisLabel: {
        fontSize: responsiveFontSize(1.1),
        color: '#666',
        textAlign: 'right',
    },
    svgContainer: {
        flex: 1,
        height: responsiveHeight(15),
        marginTop: responsiveHeight(1),
        position: 'relative',
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: responsiveHeight(0.25) },
                shadowOpacity: 0.08,
                shadowRadius: responsiveWidth(1),
            },
            android: {
                elevation: 2,
            },
        }),
    },
    svgGraph: {
        position: 'absolute',
        top: 0,
        left: 0,
    },
    dataLabels: {
        position: 'absolute',
        bottom: responsiveHeight(1),
        left: responsiveWidth(15),
        right: responsiveWidth(3),
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    labelColumn: {
        alignItems: 'center',
        flex: 1,
    },
    gridLines: {
        position: 'absolute',
        top: responsiveHeight(1),
        left: responsiveWidth(15),
        right: responsiveWidth(3),
        height: responsiveHeight(15),
    },
    gridLine: {
        position: 'absolute',
        left: 0,
        right: 0,
        height: 1,
        backgroundColor: '#E0E0E0',
        opacity: 0.5,
    },
    chartPoints: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'space-between',
        width: '100%',
        height: '100%',
        zIndex: 1,
    },
    chartPoint: {
        flex: 1,
        alignItems: 'center',
        marginHorizontal: responsiveWidth(0.2),
        height: '100%',
        justifyContent: 'space-between',
    },
    stepValue: {
        fontSize: responsiveFontSize(1.2),
        color: '#888888',
        fontWeight: '600',
        marginBottom: responsiveHeight(0.5),
        textAlign: 'center',
    },
    pointContainer: {
        width: '100%',
        height: responsiveHeight(12),
        position: 'relative',
        alignItems: 'center',
        justifyContent: 'flex-end',
    },
    dataPoint: {
        width: responsiveWidth(2.5),
        height: responsiveWidth(2.5),
        borderRadius: responsiveWidth(1.25),
        position: 'absolute',
        zIndex: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 3,
    },
    connectionLine: {
        position: 'absolute',
        backgroundColor: '#4BC16B',
        height: 2,
        left: responsiveWidth(1.25),
        transformOrigin: 'left center',
        zIndex: 1,
    },
    connectionLines: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: responsiveWidth(2),
        paddingVertical: responsiveHeight(1),
        zIndex: 2,
    },
    verticalLine: {
        width: responsiveWidth(0.5),
        backgroundColor: '#4BC16B',
        borderRadius: responsiveWidth(0.25),
        opacity: 0.6,
    },
    dateLabel: {
        fontSize: responsiveFontSize(1.1),
        color: '#888',
        textAlign: 'center',
    },
})

export default styles
